### ISSUE TITLE
Python 2 vs. 3

### ISSUE THREAD

**Issue by rochelleterman** [rochelleterman/PS239T#69]
The materials are written in Python 2.7 . But the course might benefit from switching to Python 3x. The main difference is that print() is a function in Python 3. Also encodings are better. I switched the webscraping and API tutorials to Python 3 for [this repo](https://github.com/rochelleterman/scrape-interwebz) and things seemed to work out fine.

**Comment by ribernhard** [comment]
Barring any major package conflicts, plan to use 3. Need to go through and update ipython notebook and markdown files accordingly. Double-check all packages! Make another file listing all packages used in course so we can keep track of issues with later updates/versions.

**Comment by ribernhard** [comment]
Remember to change the installation instructions too!

**Comment by ribernhard** [comment]
Rochelle will send notes on how to easily update from 2 to 3!

**Comment by rochelleterman** [comment]
To create a python 3 environment, use the commands outlined [here](https://www.continuum.io/blog/developer-blog/python-3-support-anaconda)

In brief:
Open up a terminal. You can be anywhere for this to work. The first time you do this, you need to create a python 3 environment (here it's called "py3k"):

`$ conda create -n py3k python=3 anaconda`

Then you activate that environment by typing
`$ source activate py3k`

At that point you should now see an indication that you are in `py3k`. At which point you can spin up an ipython notebook and it will use a python 3 kernel. You can also `cd` into wherever or do any of your bash things. Python 3 will be used until you end the environment or close the terminal window.

**Comment by rochelleterman** [comment]
Note that the `03_python-basics/madlib.py` script will break in Python 3.

**Comment by rochelleterman** [comment]
Here's the edited madlib.py for Python 3

```
"""
String Substitution for a Mad Lib
Adapted from code by Kirby Urner
"""                                                  

story = """                                       
Once upon a time, deep in an ancient jungle,
there lived a %(animal)s.  This %(animal)s
liked to eat %(food)s, but the jungle had
very little %(food)s to offer.  One day, an
explorer found the %(animal)s and discovered
it liked %(food)s.  The explorer took the
%(animal)s back to %(city)s, where it could
eat as much %(food)s as it wanted.  However,
the %(animal)s became homesick, so the
explorer brought it back to the jungle,
leaving a large supply of %(food)s.

The End
"""                                                 

def tellStory():                                     
    userPicks = dict()                              
    addPick('animal', userPicks)            
    addPick('food', userPicks)            
    addPick('city', userPicks)            
    print(story % userPicks)                        

def addPick(cue, dictionary):
    prompt = "Enter a specific example for %s: " % cue     
    dictionary[cue] = input(prompt)                                                             

tellStory()                                         
input("Press Enter to end the program.")        


```
