### ISSUE TITLE
Department Marketing

### ISSUE THREAD

**Issue by ribernhard** [rochelleterman/PS239T#70]

**Comment by rochelleterman** [comment]
Here's the email I sent last year. It needs updating, obviously. 

Turns out I never sent out a mass email to all departments -- I just had friends in various depts spread the word. One thing we can do is email last year's students and have them spread the word to their own departments. 

> Hello fellow grad students,
> 
> I'm writing to tell you about a new grad course that I'm teaching with Professor Laura Stoker, PS239T: Introduction to Computational Tools and Techniques. The 4 unit course will be offered Fall 2016 (it says 2 credits on the schedule, but it's really 4.)
> 
> The course is meant to springboard students into programming for social science and digital humanities research. We'll be programming Python and R, with applications in computational text analysis, webscraping, collecting data via APIs, etc. It is geared for students who have no background in programming or computer science. It will be a very 'hands on' and practically-oriented course.
> 
> I want to especially encourage incoming first year students to sign up, as it will be helpful in later methods courses. But the class is open to students of any level, in any field, with any methodological bent. 
> 
> A draft syllabus is attached. 
> 
> If you have any questions or concerns, please don't hesitate to email me.
> 
> All the best,
> Rochelle

**Comment by ribernhard** [comment]
Quick Q - why does it show up as only 2 units? I checked and it's the same
this year...

**Comment by rochelleterman** [comment]
Ugh, really? You should email Stephanie and tell her to change it. I think it's because the very first time PS239T was offered (7 years ago) it was a 2 credit course so many that's "stuck" as a default.

**Comment by ribernhard** [comment]
Emailed. Can you send me a list of emails for last year's students?

**Comment by rochelleterman** [comment]
Just emailed you last year's roster.
